CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    NAME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USERS_EMAIL
ON USERS (EMAIL);

CREATE TABLE PROJECTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    USER_ID UUID NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROJECTS_USER
                      FOREIGN KEY (USER_ID)
                      REFERENCES USERS (ID)
                      ON DELETE CASCADE
);

CREATE INDEX IDX_PROJECTS_USER_ID
ON PROJECTS (USER_ID);

CREATE TABLE TASKS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    USER_ID UUID NOT NULL,
    PROJECT_ID UUID,
    TITLE VARCHAR (255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR (20) NOT NULL DEFAULT 'TO DO',
    PRIORITY VARCHAR (20) NOT NULL DEFAULT 'MEDIUM',
    DUE_DATE TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHECK_TASK_STATUS
                   CHECK (
                       STATUS IN (
                           'TO DO',
                           'IN_PROGRESS',
                           'COMPLETED',
                           'CANCELLED'
                           )
                       ),
    CONSTRAINT CHECK_TASK_PRIORITY
                   CHECK (
                       PRIORITY IN (
                           'LOW',
                           'MEDIUM',
                           'HIGH',
                           'URGENT'
                           )
                       )
);

CREATE INDEX IDX_TASKS_USER_ID
ON TASKS (USER_ID);

CREATE INDEX IDX_TASKS_PROJECT_ID
ON TASKS (PROJECT_ID);

CREATE INDEX IDX_TASK_STATUS
ON TASKS (STATUS);

CREATE INDEX IDX_TASKS_DUE_DATE
ON TASKS (DUE_DATE);

CREATE INDEX IDX_TASKS_USER_STATUS
ON TASKS (USER_ID, STATUS);

CREATE INDEX IDX_TASKS_USER_DUE_DATE
ON TASKS (USER_ID, DUE_DATE);

CREATE TABLE TASK_AUDIT_LOGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    TASK_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    ACTION VARCHAR (20) NOT NULL,
    OLD_DATA JSONB,
    NEW_DATA JSONB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FOREIGN_KEY_TASK_AUDIT_TASK
                             FOREIGN KEY (TASK_ID)
                             REFERENCES TASKS (ID)
                             ON DELETE CASCADE,
    CONSTRAINT FOREIGN_KEY_TASK_AUDIT_USER
                             FOREIGN KEY (USER_ID)
                             REFERENCES USERS (ID)
                             ON DELETE CASCADE
);

CREATE INDEX IDX_TASK_AUDIT_TASK_ID
ON TASK_AUDIT_LOGS (TASK_ID);

CREATE INDEX IDX_TASK_AUDIT_USER_ID
ON TASK_AUDIT_LOGS (USER_ID);

CREATE INDEX IDX_TASK_AUDIT_CREATED_AT
ON TASK_AUDIT_LOGS (CREATED_AT);